---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install yarn deps
        run: yarn install

      - name: Build packages
        run: |
          yarn workspace @anticrm/platform run build

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4

      - name: Run tests
        run: |
          yarn test

      - name: Extract APIs
        run: |
          yarn workspace @anticrm/platform run build:docs

      - uses: actions/upload-artifact@v2
        with:
          name: extracted-api
          path: _api-extractor-temp/

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Run lint
        run: |
          yarn install
          yarn workspaces run lint

  chromatic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
