---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Start MongoDB
        if: matrix.os == 'ubuntu-latest'

        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4

      - name: Install yarn deps
        run: yarn install

      - name: Build packages
        run: |
          yarn workspace @anticrm/platform run build

      - name: Extract APIs
        run: |
          yarn workspace @anticrm/platform run build:docs

      - uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          name: extracted-api
          path: _api-extractor-temp/

      - name: Run tests
        if: matrix.os == 'ubuntu-latest'
        run: |
          yarn test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Run lint
        run: |
          yarn install
          yarn workspaces run lint

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
