name: CI

on: [push, pull_request]

jobs:
  gen-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: yarn install

      - name: Build packages
        run: |
          yarn workspace @anticrm/platform run build

      - name: Extract APIs
        run: |
          yarn workspace @anticrm/platform run build:docs

      - uses: actions/upload-artifact@v2
        with:
          name: extracted-api
          path: _api-extractor-temp/

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4

      - name: Install yarn deps
        run: yarn install

      - name: Run tests
        run: |
          yarn test
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"

      - name: Run lint
        run: |
          yarn install
          yarn workspaces run lint
